### ISSUE TITLE
IOException: java.io.IOException

### ISSUE THREAD

**Issue by ryan-haver** [ikkisoft/mFiPatchMe#1]
I'm getting the following error when patching on a new install. Perhaps related to Java version I am using?

--[ UbntmFiPatchMe v0.1 - @_ikki ]
  [*] Opening Ubiquiti mFi Controller's jar "ace.jar"
  [*] Patching "com/ubnt/ace/view/AuthFilter" class
  [*] Ready to update "ace.jar". Are you sure? (yes/no)
  >yes
  [*] Executing "jar -uvf ace.jar -C /tmp/1521176906521-0 com/ubnt/ace/view/AuthFilter.class"
  [!] IOException: java.io.IOException: Cannot run program "jar": error=2, No such file or directory

**Comment by ikkisoft** [comment]
Looks like it cannot find the _jar_ command. Is it available in the terminal? Have you installed Java JDK (and not just JRE)?

**Comment by ryan-haver** [comment]
I've uninstalled and reinstalled OpenJDK 7 and now I'm getting this:

--[ UbntmFiPatchMe v0.1 - @_ikki ]
  [*] Opening Ubiquiti mFi Controller's jar "ace.jar"
  [*] Patching "com/ubnt/ace/view/AuthFilter" class
  [*] Ready to update "ace.jar". Are you sure? (yes/no)
  >yes
  [*] Executing "jar -uvf ace.jar -C /tmp/1521205881807-0 com/ubnt/ace/view/AuthFilter.class"
  [!] An error occurred while updating the original jar  [*] Patched

**Comment by ryan-haver** [comment]
Looks good after I ran "java -jar UbntmFiPatchMe.jar -file ace.jar" with sudo.
